# Generated by Django 4.0.4 on 2022-06-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='universities',
            name='place_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='place id'),
        ),
        migrations.AlterField(
            model_name='universities',
            name='id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
    ]
